homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 32.5151
  longitude: -92.6262
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 91
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Show links to resources in log and frontend
#introduction:

wink:
    access_token: mXl2w651kQNWl-kg-wphZaP9IcYFO7U_
    #refresh_token: K9iaMo40Ya5qFwGjbCzsBfgwEZF2gpGy

#fitbit

#REST Notifications
notify:
  - name: PILLAR
    platform: rest
    resource: http://localhost/includes/getUpdates.php

# Notifying pillar that there is a state change
automation:
  trigger:
    platform: state
    entity_id: group.all_lights
  action:
    service: notify.pillar
    data:
      message: Light toggled

#grouping
group:
  Living Room: 
    view: yes
    entities:
      - light.living_room_lamp
      - light.lightstrips_1
    
  Ground Floor: 
    view: yes
    entities:
      - light.lightstrips_2
    
# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: fitbit
    monitored_resources:
      - "body/weight"
